// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Js_dict from "rescript/lib/es6/js_dict.js";

function Dynamic(Props) {
  var id = Props.id;
  var people = Js_dict.fromList({
        hd: [
          "1",
          "James"
        ],
        tl: {
          hd: [
            "2",
            "Nathan"
          ],
          tl: {
            hd: [
              "3",
              "Matthew"
            ],
            tl: /* [] */0
          }
        }
      });
  var current = Js_dict.get(people, id);
  var content = current !== undefined ? React.createElement(React.Fragment, undefined, React.createElement("div", {
              className: "uppercase bg-green-500 text-white font-bold text-sm px-2 py-1 mr-2"
            }, "Success"), React.createElement("p", {
              className: "block"
            }, " Welcome back ", React.createElement("span", {
                  className: "underline font-bold"
                }, current), " (ID: " + id + ")")) : React.createElement(React.Fragment, undefined, React.createElement("div", {
              className: "uppercase bg-red-500 text-white font-bold text-sm px-2 py-1 mr-2"
            }, "Failure"), React.createElement("p", {
              className: "block"
            }, " No person with given ID found"));
  return React.createElement("div", {
              className: "py-14 text-center"
            }, React.createElement("h1", {
                  className: "text-3xl mb-6 font-semibold"
                }, "Dynamic Routes Demonstration"), React.createElement("div", {
                  className: "flex items-center justify-center bg-slate-100 dark:bg-slate-700 p-10 rounded"
                }, content));
}

var make = Dynamic;

export {
  make ,
}
/* react Not a pure module */
