// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Feature$RescriptProjectTemplate from "../components/Feature.bs.js";

function Features(Props) {
  var features = [
    {
      title: "Rescript",
      description: "Adopted the robustly typed functional language that is reliable enough to not introduce bugs in the application if done right."
    },
    {
      title: "React",
      description: "Tha latest React 18 integrated to the stack. However, @rescript/react binding library only supports up to React 17 at the moment."
    },
    {
      title: "Tailwind CSS",
      description: "Latest Tailwind V3+ included and ready to make awesome styles in the Rescript source file itself."
    },
    {
      title: "Routing",
      description: "Server side routing has been provided. SPA routing that utilizes react-router-dom is currently unsupported."
    },
    {
      title: "Not Found Page",
      description: "A delicately crafted 404 page that hopefully reduces the amount of grunt task in development."
    },
    {
      title: "Layout",
      description: "A default layout for all the pages in the application has been provided. It can be modified in the layouts/Default.res file."
    },
    {
      title: "esbuild",
      description: "The fastest and most efficient JavaScript bundler to parse all the JS output generated by ReScript."
    },
    {
      title: "Dark Mode",
      description: "A readily made Dark Mode component utilizing Tailwind CSS is also provided."
    }
  ];
  var features$1 = Belt_Array.mapWithIndex(features, (function (index, item) {
          return React.createElement(Feature$RescriptProjectTemplate.make, {
                      index: index + 1 | 0,
                      title: item.title,
                      description: item.description
                    });
        }));
  return React.createElement("div", {
              className: "max-w-[1200px] mx-auto py-14 flex gap-9 flex-col"
            }, features$1);
}

var make = Features;

export {
  make ,
}
/* react Not a pure module */
