// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import SolfarmPng from "../assets/solfarm.png";
import * as Feature$RescriptProjectTemplate from "../components/Feature.bs.js";

var image = SolfarmPng;

function Features(Props) {
  var imageContent = function (param) {
    return React.createElement("div", {
                className: "py-5"
              }, React.createElement("h1", {
                    className: "mb-2"
                  }, "This is a source imported image that resides at src/assets/ directory."), React.createElement("img", {
                    alt: "Image",
                    src: image
                  }));
  };
  var features = [
    {
      title: "Rescript",
      description: "Adopted the robustly typed functional language that is reliable enough to not introduce bugs in the application if done right.",
      extraContents: undefined
    },
    {
      title: "React",
      description: "Tha latest React 18 integrated to the stack. However, @rescript/react binding library only supports up to React 17 at the moment.",
      extraContents: undefined
    },
    {
      title: "Tailwind CSS",
      description: "Latest Tailwind V3+ included and ready to make awesome styles in the Rescript source file itself.",
      extraContents: undefined
    },
    {
      title: "Routing",
      description: "Server side routing has been provided. SPA routing that utilizes react-router-dom is currently unsupported.",
      extraContents: undefined
    },
    {
      title: "Not Found Page",
      description: "A delicately crafted 404 page that hopefully reduces the amount of grunt task in development.",
      extraContents: undefined
    },
    {
      title: "Layout",
      description: "A default layout for all the pages in the application has been provided. It can be modified in the layouts/Default.res file.",
      extraContents: undefined
    },
    {
      title: "esbuild",
      description: "The fastest and most efficient JavaScript bundler to parse all the JS output generated by ReScript.",
      extraContents: undefined
    },
    {
      title: "Dark Mode",
      description: "A readily made Dark Mode component utilizing Tailwind CSS is also provided.",
      extraContents: undefined
    },
    {
      title: "Image Import",
      description: "Image files can be imported directly in Rescript source file.",
      extraContents: Caml_option.some(imageContent(undefined))
    }
  ];
  var features$1 = Belt_Array.mapWithIndex(features, (function (index, item) {
          return React.createElement(Feature$RescriptProjectTemplate.make, {
                      index: index + 1 | 0,
                      title: item.title,
                      description: item.description,
                      extraContents: item.extraContents
                    });
        }));
  return React.createElement("div", {
              className: "max-w-[1200px] mx-auto py-14 flex gap-9 flex-col"
            }, features$1);
}

var make = Features;

export {
  image ,
  make ,
}
/* image Not a pure module */
