// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Features(Props) {
  return React.createElement("div", undefined, React.createElement("div", undefined, "React"));
}

var make = Features;

export {
  make ,
}
/* react Not a pure module */
