// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Home(Props) {
  return React.createElement("div", {
              className: "app"
            }, React.createElement("main", {
                  className: "max-w-[1400px] mx-auto"
                }, React.createElement("h1", {
                      className: "text-6xl font-bold max-w-[70%]"
                    }, "Simple And Functional Template Built With React and Rescript")));
}

var make = Home;

export {
  make ,
}
/* react Not a pure module */
