// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import RescriptSvg from "../assets/rescript.svg";
import * as Link$RescriptProjectTemplate from "../components/Link.bs.js";
import * as Summary$RescriptProjectTemplate from "../components/Summary.bs.js";

var logo = RescriptSvg;

function Home(Props) {
  var styledA = function (text, url) {
    return React.createElement("a", {
                className: "text-[#E84F4F] hover:bg-[#f5d5d5] transition-colors duration-200 dark:hover:bg-slate-500",
                href: url
              }, text);
  };
  return React.createElement("div", {
              className: "app"
            }, React.createElement("main", {
                  className: "max-w-[1280px] mx-auto flex items-center"
                }, React.createElement("div", {
                      className: "basis-1/2 flex items-center pr-20"
                    }, React.createElement("div", {
                          className: "mr-10 w-32 h-32 shrink-0"
                        }, React.createElement("img", {
                              className: "w-full h-full",
                              alt: "Rescript logo",
                              src: logo
                            })), React.createElement("div", undefined, React.createElement("h1", {
                              className: "text-[#E84F4F] font-semibold text-4xl mb-5"
                            }, "You did it!"), React.createElement("h3", {
                              className: "text-xl mb-8"
                            }, "You've successfully created a project with ", React.createElement("span", {
                                  className: "text-[#E84F4F] hover:bg-[#f5d5d5]"
                                }, "Rescript"), " + ", React.createElement("span", {
                                  className: "text-[#E84F4F] hover:bg-[#f5d5d5]"
                                }, "React"), ". What's next?"), React.createElement("nav", undefined, React.createElement("ul", {
                                  className: "flex gap-1"
                                }, React.createElement("li", undefined, React.createElement(Link$RescriptProjectTemplate.make, {
                                          to: "/",
                                          className: "pr-3 hover:text-[#E84F4F] transition-colors duration-200",
                                          children: "Home"
                                        })), React.createElement("li", undefined, React.createElement(Link$RescriptProjectTemplate.make, {
                                          to: "/features",
                                          className: "border-l border-solid border-gray-200 dark:border-gray-600 px-3 hover:text-[#E84F4F] transition-colors duration-200",
                                          children: "Features"
                                        })), React.createElement("li", undefined, React.createElement(Link$RescriptProjectTemplate.make, {
                                          to: "/404",
                                          className: "border-l border-solid border-gray-200 dark:border-gray-600 px-3 hover:text-[#E84F4F] transition-colors duration-200",
                                          children: "404"
                                        })))))), React.createElement("div", {
                      className: "basis-1/2"
                    }, React.createElement(Summary$RescriptProjectTemplate.make, {
                          title: "Rescript + React",
                          icon: "default",
                          children: React.createElement("p", undefined, "React's powerful infrastructure paired with Rescript's robustly typed language system to propel web application development to the next level. React's ", styledA("official documentation", "https://reactjs.org/docs/getting-started.html"), " and Rescript's ", styledA("official documentation", "https://rescript-lang.org/docs/manual/latest/introduction"), " for more details.")
                        }), React.createElement(Summary$RescriptProjectTemplate.make, {
                          title: "Esbuild",
                          icon: "hammer",
                          children: React.createElement("p", undefined, "Blazingly fast JavaScript bundler faster than most of its competitors such as Webpack, Parcel and Rollup. Read the ", styledA("user manual", "https://esbuild.github.io/"), " to learn more.")
                        }), React.createElement(Summary$RescriptProjectTemplate.make, {
                          title: "Tailwind CSS",
                          icon: "tailwind",
                          children: React.createElement("p", undefined, "Styling web applications without leaving the markup. Skip convoluted namings to HTML elements and focus on styles. Take a look on the ", styledA("official documentation", "https://tailwindcss.com/docs/installation"), " to learn more about it.")
                        }), React.createElement(Summary$RescriptProjectTemplate.make, {
                          title: "Routing",
                          icon: "router",
                          children: React.createElement("p", undefined, "This template also includes routing and navigation bar made available out-of-the-box. The router used is ", styledA("Rescript Router", "https://rescript-lang.org/docs/react/latest/router"), " which is very tiny and performant. The implementation of the nav links are located within the ", React.createElement("code", {
                                    className: "font-mono underline"
                                  }, "Link.res"), " component. To navigate back from a page, simply pass in \"..\" in the \"to\" props.")
                        }), React.createElement(Summary$RescriptProjectTemplate.make, {
                          title: "Dark mode",
                          icon: "dark",
                          children: React.createElement("p", undefined, "The dark mode theming has been setup for this template with Tailwind CSS's ", styledA("class dark mode", "https://tailwindcss.com/docs/dark-mode"), ". A ready-to-use theme switcher component is readily provided. It utilizes the browser's ", styledA("Local Storage", "https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage"), " to persist the theme preference.")
                        }))));
}

var make = Home;

export {
  logo ,
  make ,
}
/* logo Not a pure module */
