// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Link$RescriptProjectTemplate from "../components/Link.bs.js";

function NotFound(Props) {
  return React.createElement("div", {
              className: "py-[150px] pt-28"
            }, React.createElement("h1", {
                  className: "text-9xl lg:text-[150px] tracking-wider text-center font-bold mb-2"
                }, 404), React.createElement("p", {
                  className: "text-xl font-semibold text-center mb-5"
                }, "Whoops... Page Not Found!!!"), React.createElement(Link$RescriptProjectTemplate.make, {
                  to: "..",
                  className: "bg-slate-700 text-gray-50 hover:bg-slate-600 rounded px-5 py-2 mx-auto w-fit block text-xl",
                  children: "Take me back"
                }));
}

var make = NotFound;

export {
  make ,
}
/* react Not a pure module */
