// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function NotFound(Props) {
  return React.createElement("div", {
              className: "py-[150px]  pt-28"
            }, React.createElement("h1", {
                  className: "text-9xl text-center font-bold mb-10"
                }, 404), React.createElement("p", {
                  className: "text-3xl font-semibold text-center mb-5"
                }, "The page that you are looking for could not be found"), React.createElement("a", {
                  className: "border-2 border-solid border-white rounded px-5 py-2 mx-auto w-fit block text-2xl",
                  href: "/"
                }, "Take me back"));
}

var make = NotFound;

export {
  make ,
}
/* react Not a pure module */
