// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Header(Props) {
  return React.createElement("div", {
              className: "py-5 bg-gray-100 "
            }, React.createElement("header", {
                  className: "flex max-w-[1400px] mx-auto justify-between"
                }, React.createElement("div", {
                      className: "text-3xl font-semibold"
                    }, "React + Rescript"), React.createElement("div", undefined, "Right")));
}

var make = Header;

export {
  make ,
}
/* react Not a pure module */
