// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.bs.js";

function Link(Props) {
  var to = Props.to;
  var className = Props.className;
  var children = Props.children;
  return React.createElement("a", {
              className: className,
              href: to,
              onClick: (function ($$event) {
                  $$event.preventDefault();
                  RescriptReactRouter.push(to);
                })
            }, children);
}

var make = Link;

export {
  make ,
}
/* react Not a pure module */
