// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Dom_storage from "rescript/lib/es6/dom_storage.js";

function ThemeSwitcher(Props) {
  var value = Dom_storage.getItem("theme", localStorage);
  var localStorageTheme = value !== undefined ? value : "light";
  var match = React.useState(function () {
        return localStorageTheme;
      });
  var setTheme = match[1];
  var theme = match[0];
  var switchTheme = function (param) {
    var newTheme;
    switch (theme) {
      case "dark" :
          document.documentElement.classList.remove("dark");
          newTheme = "light";
          break;
      case "light" :
          var _newTheme = "dark";
          document.documentElement.classList.add(_newTheme);
          newTheme = _newTheme;
          break;
      default:
        document.documentElement.classList.remove("dark");
        newTheme = "light";
    }
    Dom_storage.setItem("theme", newTheme, localStorage);
    Curry._1(setTheme, (function (param) {
            return newTheme;
          }));
  };
  return React.createElement("button", {
              className: "block",
              onClick: switchTheme
            }, React.createElement("svg", {
                  height: "24",
                  width: "24",
                  fill: "currentColor",
                  viewBox: "0 0 16 16",
                  xmlns: "http://www.w3.org/2000/svg"
                }, React.createElement("path", {
                      d: "M12 8a4 4 0 1 1-8 0 4 4 0 0 1 8 0zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"
                    })));
}

var make = ThemeSwitcher;

export {
  make ,
}
/* react Not a pure module */
