// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function App(Props) {
  var name = "Andres";
  var element = name !== undefined ? React.createElement("div", undefined, "Hello " + name + "") : null;
  return React.createElement("div", {
              className: "app"
            }, element, React.createElement("div", {
                  className: "bg-gray-400 font-mono"
                }, "This is styled"));
}

var make = App;

export {
  make ,
}
/* react Not a pure module */
