import "./index.bs";

/*
 *  This is the entry point for the React Scripts
 *
 *  Do not edit this file directly. Edit index.res and it will compile
 *  into index.bs.js which utimately reach here via imports above.
 *
 */
