// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Header$RescriptProjectTemplate from "../components/Header.bs.js";

function Default(Props) {
  var children = Props.children;
  return React.createElement("div", {
              className: "bg-gradient-to-br from-cyan-600 to-violet-400 min-h-screen"
            }, React.createElement(Header$RescriptProjectTemplate.make, {}), children);
}

var make = Default;

export {
  make ,
}
/* react Not a pure module */
