// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Header$RescriptProjectTemplate from "../components/Header.bs.js";

function Default(Props) {
  var children = Props.children;
  return React.createElement("div", {
              className: "min-h-screen flex place-items-center"
            }, React.createElement(Header$RescriptProjectTemplate.make, {}), React.createElement("main", {
                  className: "md:max-w-[1400px] mx-auto my-auto"
                }, children));
}

var make = Default;

export {
  make ,
}
/* react Not a pure module */
